# Clase 3 - Python

## Ciclo While

In [1]:
i = 1
while i < 6:
  print(i)
  i += 1

1
2
3
4
5


## Ejercicios

1. Crear un programa que permita al usuario ingresar los montos de las compras de un cliente (se desconoce la cantidad de datos que cargará, la cual puede cambiar en cada ejecución), cortando el ingreso de datos cuando el usuario ingrese el monto 0. Si ingresa un monto negativo, no se debe procesar y se debe pedir que ingrese un nuevo monto. Al finalizar, informar el total a pagar teniendo que cuenta que, si las ventas superan el total de \$1000, se le debe aplicar un 10\% de descuento.

2. Use un bucle para mostrar elementos de una lista dada que estén presentes en posiciones pares

In [ ]:
lista = [435,765,23,645,876,234,6,7867,232,3546,5232,334,65,8,56,345,7568,568,678,32,564]

## Librerías para Data Analytics pandas

### Numpy

Documentación: [Click Aquí](https://numpy.org/doc/1.24/)

NumPy es una librería de Python especializada en el cálculo numérico y el análisis de datos, especialmente para un gran volumen de datos.

Incorpora una nueva clase de objetos llamados arrays que permite representar colecciones de datos de un mismo tipo en varias dimensiones, y funciones muy eficientes para su manipulación.

La ventaja de Numpy frente a las listas predefinidas en Python es que el procesamiento de los arrays se realiza mucho más rápido (hasta 50 veces más) que las listas, lo cual la hace ideal para el procesamiento de vectores y matrices de grandes dimensiones.

![numpy](https://aprendeconalf.es/docencia/python/manual/img/numpy-logo.png)

![numpy](https://aprendeconalf.es/docencia/python/manual/img/arrays.png)


#### Importemos la librería

In [15]:
import numpy as np

In [16]:
np.array([1, 2, 3])

array([1, 2, 3])

In [17]:
np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
np.empty((1,2,3))

array([[[0.0e+000, 4.9e-324, 6.9e-323],
        [7.4e-323, 7.9e-323, 8.4e-323]]])

In [19]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [20]:
np.ones((4,5,6))

array([[[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]])

In [21]:
np.full((1,5), 'hola')

array([['hola', 'hola', 'hola', 'hola', 'hola']], dtype='<U4')

In [24]:
np.identity((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
np.random.random((2,34))

array([[0.00720375, 0.0897966 , 0.21215577, 0.92517118, 0.24247672,
        0.18197989, 0.83847972, 0.74937152, 0.67120088, 0.847503  ,
        0.69222034, 0.06175389, 0.05467178, 0.56864101, 0.82432215,
        0.99324202, 0.18388169, 0.52770994, 0.00524738, 0.72173772,
        0.71707187, 0.95124449, 0.00572262, 0.35486641, 0.95646286,
        0.29281398, 0.92401166, 0.1453185 , 0.11543839, 0.20150228,
        0.5004737 , 0.48140122, 0.50837985, 0.18129085],
       [0.10394259, 0.62785141, 0.980106  , 0.51093628, 0.53753422,
        0.7377213 , 0.28202689, 0.40862938, 0.80386466, 0.2210309 ,
        0.20715999, 0.52554965, 0.67053975, 0.99508579, 0.39779904,
        0.54683482, 0.08738128, 0.80292226, 0.61862873, 0.11180437,
        0.86079756, 0.7920933 , 0.86890265, 0.86214846, 0.92455235,
        0.99850659, 0.32744553, 0.96981107, 0.7870046 , 0.0575617 ,
        0.114854  , 0.26383364, 0.71555583, 0.20726669]])

#### Atributos de un array

1. **a.ndim** : Devuelve el número de dimensiones del array a.

2. **a.shape** : Devuelve una tupla con las dimensiones del array a.

3. **a.size** : Devuelve el número de elementos del array a.

4. **a.dtype**: Devuelve el tipo de datos de los elementos del array a.

In [ ]:
a1 = np.array([1, 2, 3])


### Pandas

Documentación: [Click Aquí](https://pandas.pydata.org/docs/user_guide/index.html)

Las principales características de esta librería son:

- Define nuevas estructuras de datos basadas en los arrays de la librería NumPy pero con nuevas funcionalidades.
- Permite leer y escribir fácilmente ficheros en formato CSV, Excel y bases de datos SQL.
- Permite acceder a los datos mediante índices o nombres para filas y columnas.
- Ofrece métodos para reordenar, dividir y combinar conjuntos de datos.
- Permite trabajar con series temporales.
- Realiza todas estas operaciones de manera muy eficiente.

- **Series**: array unidimensional etiquetado capaz de almacenar cualquier tipo de dato.
- **DataFrame**: estructura bidimensional con columnas que pueden ser también de cualquier tipo. Estas columnas son a su vez Series.

![pandas](https://profile.es/wp-content/media/Estructuras-de-datos-en-Pandas-1.png)


### Series

In [26]:
s = pd.Series(['Matemáticas', 'Historia', 'Economía', 'Programación', 'Inglés'], dtype='string')
print(s)

0     Matemáticas
1        Historia
2        Economía
3    Programación
4          Inglés
dtype: string


In [27]:
s = pd.Series({'Matemáticas': 6.0,  'Economía': 4.5, 'Programación': 8.5})
print(s)

Matemáticas     6.0
Economía        4.5
Programación    8.5
dtype: float64


- s.count()
- s.sum()
- s.cumsum()
- s.value_counts()
- s.value_counts(normalize=True)
- s.min()
- s.max()
- s.mean()
- s.var()
- s.std()
- s.describe() 

In [ ]:
s = pd.Series([1, 1, 1, 1, 2, 2, 2, 3, 3, 4])

### DataFrame

In [29]:
datos = {'nombre':['María', 'Luis', 'Carmen', 'Antonio'],
         'edad':[18, 22, 20, 21],
         'grado':['Economía', 'Medicina','Arquitectura', 'Economía'],
         'correo':['maria@gmail.com', 'luis@yahoo.es', 'carmen@gmail.com', 'antonio@gmail.com']}

In [30]:
pd.DataFrame(datos)

nombre  edad         grado             correo
0    María    18      Economía    maria@gmail.com
1     Luis    22      Medicina      luis@yahoo.es
2   Carmen    20  Arquitectura   carmen@gmail.com
3  Antonio    21      Economía  antonio@gmail.com

In [31]:
pd.DataFrame(np.random.randn(4, 3), columns=['a', 'b', 'c'])

a         b         c
0 -0.261888 -0.843963 -1.290922
1 -1.300587 -0.874607  0.205374
2  0.495178  1.125115 -0.587208
3  1.629117  1.056210 -0.205514

- df.info() : Devuelve información (número de filas, número de columnas, índices, tipo de las columnas y memoria usado) sobre el DataFrame df.

- df.shape : Devuelve una tupla con el número de filas y columnas del DataFrame df.

- df.size : Devuelve el número de elementos del DataFrame.

- df.columns : Devuelve una lista con los nombres de las columnas del DataFrame df.

- df.index : Devuelve una lista con los nombres de las filas del DataFrame df.

- df.dtypes : Devuelve una serie con los tipos de datos de las columnas del DataFrame df.

- df.head(n) : Devuelve las n primeras filas del DataFrame df.

- df.tail(n) : Devuelve las n últimas filas del DataFrame df.

In [12]:
df = pd.read_csv('data.csv')

In [13]:
df.head(10)

date      price  bedrooms  bathrooms  sqft_living  sqft_lot  \
0  02-05-2014 0:00   313000.0       3.0       1.50       1340.0    7912.0   
1  02-05-2014 0:00  2384000.0       5.0       2.50       3650.0    9050.0   
2  02-05-2014 0:00   342000.0       3.0       2.00       1930.0   11947.0   
3  02-05-2014 0:00   420000.0       3.0       2.25       2000.0    8030.0   
4  02-05-2014 0:00   550000.0       4.0       2.50       1940.0   10500.0   
5  02-05-2014 0:00   490000.0       2.0       1.00        880.0    6380.0   
6  02-05-2014 0:00   335000.0       2.0       2.00       1350.0    2560.0   
7  02-05-2014 0:00   482000.0       4.0       2.50       2710.0   35868.0   
8  02-05-2014 0:00   452500.0       3.0       2.50       2430.0   88426.0   
9  02-05-2014 0:00   640000.0       4.0       2.00       1520.0    6200.0   

   floors  waterfront  view  condition  sqft_above  sqft_basement  yr_built  \
0     1.5         0.0   0.0        3.0      1340.0            0.0    1955.0   
1     2.0         0.0   4.0        5.0      3370.0          280.0    1921.0   
2     1.0         0.0   0.0        4.0      1930.0            0.0    1966.0   
3     1.0         0.0   0.0        4.0      1000.0         1000.0    1963.0   
4     1.0         0.0   0.0        4.0      1140.0          800.0    1976.0   
5     1.0         0.0   0.0        3.0       880.0            0.0    1938.0   
6     1.0         0.0   0.0        3.0      1350.0            0.0    1976.0   
7     2.0         0.0   0.0        3.0      2710.0            0.0    1989.0   
8     1.0         0.0   0.0        4.0      1570.0          860.0    1985.0   
9     1.5         0.0   0.0        3.0      1520.0            0.0    1945.0   

   yr_renovated                    street          city  statezip country  
0        2005.0      18810 Densmore Ave N     Shoreline  WA 98133     USA  
1           0.0           709 W Blaine St       Seattle  WA 98119     USA  
2           0.0  26206-26214 143rd Ave SE          Kent  WA 98042     USA  
3           0.0           857 170th Pl NE      Bellevue  WA 98008     USA  
4        1992.0         9105 170th Ave NE       Redmond  WA 98052     USA  
5        1994.0            522 NE 88th St       Seattle  WA 98115     USA  
6           0.0         2616 174th Ave NE       Redmond  WA 98052     USA  
7           0.0         23762 SE 253rd Pl  Maple Valley  WA 98038     USA  
8           0.0   46611-46625 SE 129th St    North Bend  WA 98045     USA  
9        2010.0          6811 55th Ave NE       Seattle  WA 98115     USA

In [14]:
df.isna().sum()

date              0
price             0
bedrooms          0
bathrooms         0
sqft_living       6
sqft_lot          6
floors            6
waterfront        5
view              5
condition         5
sqft_above       18
sqft_basement     5
yr_built          1
yr_renovated      1
street            1
city              0
statezip          0
country           0
dtype: int64