# Diego Yáñez
## Tarea Enunciado 2 : Synchronous Machine Data Set Data Set
Los motores sincrónicos (SMs) son motores de corriente alterna con velocidad constante. La base de datos es obtenida a partir del entorno de operaciones de un experimento real. La tarea es crear un modelo para estimar la corriente de excitación de los motores sincrónicos.



## Descripción de la base de datos
Los atributos presentes en la base de datos son los siguientes:


1.    **ly:** Corriente de carga (variable independiente)
2.    **PF:** Factor de potencia (variable independiente)
3.    **e:** Error del factor de potencia (variable independiente)
4.    **dIf** Cambio de la corriente de excitación de la máquina síncronica (variable independiente)
5.    **If**: Corriente de excitación de la máquina síncrona (variable dependiente)

## Lectura de la data e impresión

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive/', force_remount=True)


Mounted at /content/gdrive/


In [ ]:
# Load CSV using Pandas
import pandas as pd
filename = "/content/gdrive/MyDrive/ClaseProcesamiento/data/synchronous_machine.csv"
df = pd.read_csv(filename,sep=";")
print(df)


      lf    pf     e    dif     if
0    3.0  0.66  0.34  0.383  1.563
1    3.0  0.68  0.32  0.372  1.552
2    3.0  0.70  0.30  0.360  1.540
3    3.0  0.72  0.28  0.338  1.518
4    3.0  0.74  0.26  0.317  1.497
..   ...   ...   ...    ...    ...
552  6.0  0.91  0.09  0.142  1.322
553  6.0  0.93  0.07  0.151  1.331
554  6.0  0.95  0.05  0.160  1.340
555  6.0  0.97  0.03  0.160  1.340
556  6.0  0.99  0.01  0.160  1.340

[557 rows x 5 columns]


## Librerias

In [ ]:
#importing libraries
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

## Dividir X_reg y Y_reg en conjuntos de test y train 
Primero, separamos la base de datos en 70% train y 30% test

In [ ]:
train, test = train_test_split(df, test_size = 0.30)
print("Ejemplos usados para train: ", len(train))
print("Ejemplos usados para test: ", len(test))

Ejemplos usados para train:  389
Ejemplos usados para test:  168


Luego, obtenemos X_reg_train, Y_reg_train, X_reg_test y Y_reg_test

In [ ]:
#X_reg_traing e Y_reg_train
array_train= train.values
x_reg_train= array_train[:,0:4]
y_reg_train= array_train[:,4]
print("Los valores X usados para train son: \n ", x_reg_train,"\n")
print("----------------------------------------------------------------------")
print("Los valores Y usados para train son: \n ", y_reg_train, "\n")

Los valores X usados para train son: 
  [[6.    0.99  0.01  0.16 ]
 [3.4   0.82  0.18  0.238]
 [5.3   0.65  0.35  0.697]
 ...
 [3.7   0.72  0.28  0.419]
 [4.8   0.65  0.35  0.622]
 [4.6   0.93  0.07  0.188]] 

----------------------------------------------------------------------
Los valores Y usados para train son: 
  [1.34  1.418 1.877 1.773 1.634 1.586 1.276 1.38  1.541 1.846 1.342 1.679
 1.575 1.529 1.325 1.354 1.361 1.41  1.44  1.756 1.275 1.28  1.674 1.87
 1.795 1.622 1.468 1.406 1.565 1.61  1.39  1.79  1.296 1.297 1.688 1.57
 1.257 1.732 1.785 1.403 1.364 1.61  1.497 1.339 1.342 1.348 1.361 1.415
 1.539 1.333 1.616 1.706 1.753 1.344 1.594 1.297 1.92  1.732 1.589 1.667
 1.714 1.949 1.398 1.661 1.633 1.375 1.575 1.802 1.276 1.786 1.337 1.824
 1.256 1.832 1.369 1.535 1.908 1.454 1.35  1.854 1.622 1.549 1.275 1.313
 1.38  1.377 1.618 1.587 1.32  1.405 1.465 1.586 1.342 1.396 1.304 1.772
 1.37  1.711 1.625 1.377 1.466 1.381 1.726 1.582 1.775 1.563 1.699 1.426
 1.558 1.476 1.257 1.617

In [ ]:
#X_reg_test e Y_reg_test
array_test= test.values
x_reg_test= array_test[:,0:4]
y_reg_test= array_test[:,4]
print("Los valores X usados para test son: \n ", x_reg_test,"\n")
print("------------------------------------------------------------------------")
print("Los valores Y usados para test son: \n ", y_reg_test, "\n")

Los valores X usados para test son: 
  [[4.7   0.79  0.21  0.49 ]
 [4.7   0.97  0.03  0.185]
 [4.1   0.72  0.28  0.489]
 [5.3   0.77  0.23  0.513]
 [4.5   0.92  0.08  0.084]
 [5.3   0.87  0.13  0.305]
 [5.8   0.99  0.01  0.218]
 [4.3   0.82  0.18  0.34 ]
 [4.7   0.87  0.13  0.288]
 [4.9   0.99  0.01  0.14 ]
 [4.7   0.89  0.11  0.297]
 [3.7   0.66  0.34  0.453]
 [5.8   0.79  0.21  0.575]
 [5.2   0.77  0.23  0.524]
 [4.2   0.9   0.1   0.282]
 [6.    0.79  0.21  0.538]
 [5.2   0.99  0.01  0.223]
 [5.6   0.83  0.17  0.499]
 [3.9   1.    0.    0.097]
 [3.5   0.94  0.06  0.052]
 [3.1   0.74  0.26  0.385]
 [3.4   0.78  0.22  0.306]
 [5.    0.79  0.21  0.442]
 [4.7   0.77  0.23  0.473]
 [4.    0.92  0.08  0.064]
 [4.5   0.94  0.06  0.092]
 [3.6   0.9   0.1   0.261]
 [4.8   0.97  0.03  0.162]
 [3.9   0.74  0.26  0.418]
 [3.7   0.92  0.08  0.123]
 [4.1   0.86  0.14  0.263]
 [5.    0.67  0.33  0.573]
 [6.    0.87  0.13  0.29 ]
 [5.9   0.83  0.17  0.454]
 [3.6   1.    0.    0.162]
 [3.3   1.    0.

## Regresiones 
Se entrenan los modelos con el 70% y se prueban sobre el otro 30% de la base de datos

### Regresión Lineal


In [ ]:
# Linear Regression
from sklearn.linear_model import LinearRegression

kfold = KFold(n_splits = 10)
model = LinearRegression()
scoring = "neg_mean_squared_error"
results = cross_val_score(model, x_reg_train, y_reg_train, cv = kfold, scoring = scoring)
print("El MSE para LiR es "+str(results.mean()))
print("-----------------------------------------------------")
model.fit(x_reg_train, y_reg_train)
y_predict = model.predict(x_reg_test)
from sklearn.metrics import r2_score

print('R2_Score: ', r2_score(y_reg_test, y_predict))
print("El modelo con todas las variables introducidas es capaz de explicar el ",r2_score(y_reg_test, y_predict)*100,"% de la variabilidad observada en la variable dependiente CORRIENTE DE EXCITACION DE LA MAQUINA SINCRONICA  \n ")
print("El intercepto del modelo es ", model.intercept_)
print("Los coeficientes del modelo son ", model.coef_ ," respectivamente" )


El MSE para LiR es -8.069256602621306e-32
-----------------------------------------------------
R2_Score:  1.0
El modelo con todas las variables introducidas es capaz de explicar el  100.0 % de la variabilidad observada en la variable dependiente CORRIENTE DE EXCITACION DE LA MAQUINA SINCRONICA  
 
El intercepto del modelo es  1.1800000000000002
Los coeficientes del modelo son  [-8.44433942e-17  2.22044605e-16 -2.08166817e-16  1.00000000e+00]  respectivamente


### Ridge Regression

In [ ]:
# Ridge 
from sklearn.linear_model import Ridge

kfold = KFold(n_splits = 10)
model = Ridge()
scoring = "neg_mean_squared_error"
results = cross_val_score(model, x_reg_train, y_reg_train, cv = kfold, scoring = scoring)
print("El MSE para LiR es "+str(results.mean()))
print("-----------------------------------------------------")
model.fit(x_reg_train, y_reg_train)
y_predict = model.predict(x_reg_test)
from sklearn.metrics import r2_score

print('R2_Score: ', r2_score(y_reg_test, y_predict))
print("El modelo con todas las variables introducidas es capaz de explicar el ",r2_score(y_reg_test, y_predict)*100,"% de la variabilidad observada en la variable dependiente CORRIENTE DE EXCITACION DE LA MAQUINA SINCRONICA  \n ")
print("El intercepto del modelo es ", model.intercept_)
print("Los coeficientes del modelo son ", model.coef_ ," respectivamente" )


El MSE para LiR es -0.00037194491605673245
-----------------------------------------------------
R2_Score:  0.9892773975175592
El modelo con todas las variables introducidas es capaz de explicar el  98.92773975175592 % de la variabilidad observada en la variable dependiente CORRIENTE DE EXCITACION DE LA MAQUINA SINCRONICA  
 
El intercepto del modelo es  1.310496750709392
Los coeficientes del modelo son  [ 0.02355795 -0.20199969  0.20199969  0.70045736]  respectivamente


### LASSO Regression

In [ ]:
# LASSO Regression
# Ridge 
from sklearn.linear_model import Lasso

kfold = KFold(n_splits = 10)
model = Lasso()
scoring = "neg_mean_squared_error"
results = cross_val_score(model, x_reg_train, y_reg_train, cv = kfold, scoring = scoring)
print("El MSE para LiR es "+str(results.mean()))
print("-----------------------------------------------------")
model.fit(x_reg_train, y_reg_train)
y_predict = model.predict(x_reg_test)
from sklearn.metrics import r2_score

print('R2_Score: ', r2_score(y_reg_test, y_predict))
print("El modelo con todas las variables introducidas es capaz de explicar el ",r2_score(y_reg_test, y_predict)*100,"% de la variabilidad observada en la variable dependiente CORRIENTE DE EXCITACION DE LA MAQUINA SINCRONICA  \n ")
print("El intercepto del modelo es ", model.intercept_)
print("Los coeficientes del modelo son ", model.coef_ ," respectivamente" )


El MSE para LiR es -0.0337859197386831
-----------------------------------------------------
R2_Score:  -5.8500559114271766e-05
El modelo con todas las variables introducidas es capaz de explicar el  -0.005850055911427177 % de la variabilidad observada en la variable dependiente CORRIENTE DE EXCITACION DE LA MAQUINA SINCRONICA  
 
El intercepto del modelo es  1.5302596401028277
Los coeficientes del modelo son  [ 0. -0.  0.  0.]  respectivamente


### ElasticNet Regression

In [ ]:
# ElasticNet Regression

from sklearn.linear_model import ElasticNet


kfold = KFold(n_splits = 10, random_state = 4565, shuffle = True)
model = ElasticNet()
scoring = "neg_mean_squared_error"
results = cross_val_score(model, x_reg_train, y_reg_train, cv = kfold, scoring = scoring)
print("El MSE para LiR es "+str(results.mean()))
print("-----------------------------------------------------")
model.fit(x_reg_train, y_reg_train)

y_predict = model.predict(x_reg_test)
from sklearn.metrics import r2_score

print('R2_Score: ', r2_score(y_reg_test, y_predict))
print("El modelo con todas las variables introducidas es capaz de explicar el ",r2_score(y_reg_test, y_predict)*100,"% de la variabilidad observada en la variable dependiente CORRIENTE DE EXCITACION DE LA MAQUINA SINCRONICA  \n ")
print("El intercepto del modelo es ", model.intercept_)
print("Los coeficientes del modelo son ", model.coef_ ," respectivamente" )

El MSE para LiR es -0.03387318701878769
-----------------------------------------------------
R2_Score:  -5.8500559114271766e-05
El modelo con todas las variables introducidas es capaz de explicar el  -0.005850055911427177 % de la variabilidad observada en la variable dependiente CORRIENTE DE EXCITACION DE LA MAQUINA SINCRONICA  
 
El intercepto del modelo es  1.5302596401028277
Los coeficientes del modelo son  [ 0. -0.  0.  0.]  respectivamente


[[3.5   0.68  0.32  0.395]
 [5.9   0.71  0.29  0.621]
 [3.2   0.8   0.2   0.338]
 ...
 [5.5   0.79  0.21  0.499]
 [3.8   0.82  0.18  0.287]
 [4.9   0.73  0.27  0.536]]
